### ISSUE TITLE
Xlights crashing when rendering packaged/purchased sequence

### ISSUE THREAD

**Issue by whybecausewhy** [xLightsSequencer/xLights#3565]
I am a member of Pixel Pro Displays and I have one sequence of the dozen I downloaded from them that crashes once I add the matrix and megatrees..  Attached is the crash report zip.  Any help would be appreciated
[xLights_dbgrpt-12840-20221114T201256.zip](https://github.com/smeighan/xLights/files/10008635/xLights_dbgrpt-12840-20221114T201256.zip)

**Comment by keithsw1111** [comment]
The crash report shows a call stack that looks corrupted so without the actual files to reproduce the problem there is not much we can do. Please do not upload vendor sequences here.

**Comment by merryoncherry** [comment]
Which PPD sequence is it?  There's some chance we might have it without posting it.

**Comment by derwin12** [comment]
Looking like Glee The RoofTop. Some talk on their fb group about hardware decoding crashing on some videos - but this is flagged as a software decoding.
```
[DEBUG] Software decoding enabled for codec 'raw video'
2022-11-14 20:12:52,565 15044 log_base [INFO] Video loaded: C:\Users\cjloc\cjlocey Drive\Pixel Lights\Oakbrook\ImportedMedia\Glee - Deck The Rooftop_Pro Layout\Videos\Mega Tree S2.avi
2022-11-14 20:12:52,565 15044 log_base
```

**Comment by whybecausewhy** [comment]
email me direct and I can send you the zip file
    On Tuesday, November 15, 2022 at 06:59:04 AM CST, Keith Westley ***@***.***> wrote:  
 
 


The crash report shows a call stack that looks corrupted so without the actual files to reproduce the problem there is not much we can do. Please do not upload vendor sequences here.

**Comment by whybecausewhy** [comment]
Any update?

**Comment by whybecausewhy** [comment]
I sent it to Keith at a hotmail address
I can send it to you if you email me

**Comment by whybecausewhy** [comment]
Also per a recommendation from Clyde, I just tried to delete the video from the matrix and mega tree that he thinks might be the issue and deleting the first row with the video and it crashed while deleting

**Comment by computergeek1507** [comment]
Clyde sent it to me as well, the issue is fixed in the master already.

**Comment by whybecausewhy** [comment]
let me know when you have something for me to test.
Thanks

**Comment by derwin12** [comment]
So .. the fix would be in the nightly build or in .23 which I see is coming soon .. today?

**Comment by whybecausewhy** [comment]
Issue not resolved
[xLights_dbgrpt-18724-20221120T113222.zip](https://github.com/smeighan/xLights/files/10050309/xLights_dbgrpt-18724-20221120T113222.zip)

**Comment by whybecausewhy** [comment]
The release did not resolve my issue
    On Sunday, November 20, 2022 at 07:39:56 AM CST, Keith Westley ***@***.***> wrote:  
 
 


Closed #3565 as completed.

**Comment by keithsw1111** [comment]
I took a look at the sequence you sent me. Apart from issues with missing files it renders fine when i open it on their layout.

I then saved it then opened your layout and mapped matrix and mega tree and imported the effects and rendered no issues.

Maybe if you could be clearer about the exact mappings and how you do the import. I am importing from the xsq ... maybe you are using the more problematic zip import? Maybe i am not mapping the same things.

**Comment by whybecausewhy** [comment]
I am inporting using the zip file.  Should I import things the old way by unzipping and saving it on my PC?
    On Sunday, November 20, 2022 at 03:13:24 PM CST, Keith Westley ***@***.***> wrote:  
 
 


I took a look at the sequence you sent me. Apart from issues with missing files it renders fine when i open it on their layout.

I then saved it then opened your layout and mapped matrix and mega tree and imported the effects and rendered no issues.

Maybe if you could be clearer about the exact mappings and how you do the import. I am importing from the xsq ... maybe you are using the more problematic zip import? Maybe i am not mapping the same things.

**Comment by derwin12** [comment]
Did you want to drop in the xlightszoom.com and maybe we can see & recreate this issue?

**Comment by whybecausewhy** [comment]
Yes please
    On Sunday, November 20, 2022 at 06:28:39 PM CST, Daryl ***@***.***> wrote:  
 
 


Did you want to drop in the xlightszoom.com and maybe we can see & recreate this issue?

**Comment by joe12345567** [comment]
I had this issue also, the file names are not importing for video files.
I could import the sequence and play it after rendering however if you selected the video effect there were no file names and it turned red and stayed that way

I was able to get around this by moving my import file folder to my desktop.

Something to do with the number of sub directory's??

**Comment by derwin12** [comment]
Can this be closed?

**Comment by whybecausewhy** [comment]
Yes On Jan 16, 2024, at 8:52 AM, Daryl ***@***.***> wrote:﻿
Can this be closed?
