### ISSUE TITLE
SanDevices E680 controller page: xLights upload command unresponsive; 5.x firmware changes

### ISSUE THREAD

**Issue by scuba** [xLightsSequencer/xLights#5430]
**Describe the bug**
The SanDevices E680 controller web page does not respond to the xLights "Upload" command. This behavior has been observed regardless of the firmware version (4.x and 5.x), as the web page code was likely reused across all EPROM firmware versions. Firmware 5.x is larger than 4.x; support for TLS3001/CYT3005 pixel types was removed in 5.x to fit within EPROM constraints. The original web page code was modified by the programmer to fit within the EPROM, which may contribute to the upload command issue. Experienced xLights users (since original Nutcracker) have confirmed these behaviors and limitations.

**To Reproduce**
1. Connect to a SanDevices E680 controller (firmware 4.x or 5.x).
2. Attempt to use the "Upload" command from xLights to configure the controller.
3. Observe that the web page does not respond or process the upload from xLights.

**Expected behavior**
The E680 web interface should accept and process configuration uploads from xLights.

**Screenshots**

**Versions (please complete the following information):**
 - OS: MAC
 - xLights version 2025.06

**Additional context**
- xLights users are unable to upload controller configurations to the E680 via the web interface.
- Users requiring TLS3001/CYT3005 pixel support must remain on 4.x firmware.
- CC: Daryl, Jim St. John
- Context provided by: @scuba (xLights user since Nutcracker)

**Attachments**
- Please attach logs or package sequences if relevant.

**Comment by computergeek1507** [comment]
xLights only currently officially supports the E682 and E6804.

**Comment by computergeek1507** [comment]
If you could attach some log files, as requested in the issue template, I could look into the difference in the HTTP files to see if I can fix/support it.

**Comment by scuba** [comment]
Sure, I'm a bit new to the log features in xlights.  Is the Package Log Files the correct tool for your needs? 
Also, it may take a few days to retrieve the E680's from our storage unit, please be patient.

BTW: I ran a test of the upload xlights feature and even if it states " no connection" some seconds later it appears to slowly upload data to the controller (E682).  Some changes do appear in the controller.  The Controller Name on its webpage doesn't match the controller name in xlights.  Is that an issue?  The upload seams not to affect the webpage system information. 

In case you may not know it, the E682 can be setup as a DMX controller by using a set of jumpers.  E680's can't!.

I attached a zip file of what I think is the log files.  This is a test setup where I only have the E682 named "DMX controller" connected to a set of moving heads.  no pixels.  I've included the visualizer screenshot and the controller tab screenshot.  Ports 13,14,15, and 16 are DMX assigned ports by the use of the jumpers.

[xLightsProblem.zip](https://github.com/user-attachments/files/21080486/xLightsProblem.zip)
[Visualiser.pdf](https://github.com/user-attachments/files/21080485/Visualiser.pdf)
[Controller tab.pdf](https://github.com/user-attachments/files/21080487/Controller.tab.pdf)

**Comment by computergeek1507** [comment]
When I wrote the V5 upload I internally didn't support DMX, As you probably know the E682 has four output internally that muxed to 4 pixel ports or a single DMX port. As they are shared, this causes some design issues with the visualizer. We would have to show both as pixels and DMX ports and error if both types are used in the same grouping at the same time. Due to that problem causing more issues than it's worth I didn't add DMX support to the auto upload. If you want to use DMX on a E682, I would revert to the Universe start addressing for that specific controller. As for the name field being broken that is a bug in the firmware, it's kind of fixed in the 5.050 beta(but I wouldn't use it as there are many other bugs in the beta). For data missing that is the nature of the E682 upload, it's unreliable due to how xLights has to talk to the San device controllers. I have attempted multiple times in the last 5 years to work with John to improve it but have never got a response. Universal Start Addressing is normally the easiest solution or purchasing a new controller with better xLights integration.

**Comment by scuba** [comment]
Scott 
Thanks for the effort.  I will do the DMX either with a pixel2DMX adapter or the old fashion way of programming the controller.  John can be a bit of a challenge from time to time.  Any recommendation for the different controller?

Again Thank you for your time, John

**Comment by dkulp** [comment]
Scott:  We likely could have two "variants" in xLights... one with all pixels and one with 12 pixel strings + DMX.    That would allow it to work properly with the visualizer.    Doesn't really solve all the other issues with it though.

That said, the SanDevices are really really old.   At this point I'd really consider getting a newer, more capable controller.  (I'm certainly biased as I sell a bunch:  https://kulplights.com )

**Comment by computergeek1507** [comment]
I was thinking about adding some more variety to support DMX better. I also need to add/update the regex and controller decoding code to support the older E680 and E681. I have neither so I never tried to add them.

**Comment by scuba** [comment]
Dan, Thanks for the comments.  If it turns out I've looked at your website and I'm looking for a controller that will do DMX. do you have a suggestion as to what controller I could add to my display? (Cost would be a factor.)

**Comment by derwin12** [comment]
Going to close this as it appears Scott has this fixed up. If there is a new issue please create a new ticket.
